const activities = [
  { id: 1, text: 'TC-101 executed by Taylor Tester (Pass)', time: '10 min ago' },
  { id: 2, text: 'BUG-56 created and assigned to Chris Nolan', time: '35 min ago' },
  { id: 3, text: 'Weekly QA report generated by Avery Admin', time: '1 hour ago' },
  { id: 4, text: 'TC-205 updated with new expected result', time: '2 hours ago' },
];

const getActivities = (req, res) => {
  res.status(200).json(activities);
};

const createActivity = (req, res) => {
  const { text } = req.body;

  if (!text) {
    return res.status(400).json({ message: 'text is required' });
  }

  const newActivity = {
    id: Date.now(),
    text,
    time: 'Just now',
  };

  activities.unshift(newActivity);
  return res.status(201).json(newActivity);
};

module.exports = {
  getActivities,
  createActivity,
};
